version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
