name: Deploy to AWS
on:
  push:
    branches: [main]
jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build backend
        run: npm run build --workspace=apps/backend
      - name: Build frontend
        run: npm run build --workspace=apps/frontend
      - name: Run backend tests
        run: npm run test --workspace=apps/backend
      - name: Run frontend tests
        run: npm run test --workspace=apps/frontend
      - name: Run Playwright E2E tests
        run: npx playwright install && npx playwright test tests/e2e/ --reporter=list
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=infrastructure/aws init
      - name: Terraform Apply
        run: terraform -chdir=infrastructure/aws apply -auto-approve
      # Add Docker build/push to ECR and ECS deploy steps here as you add resources
