name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build backend
        run: npm run build --workspace=apps/backend
      - name: Build frontend
        run: npm run build --workspace=apps/frontend
      - name: Run backend tests
        run: npm run test --workspace=apps/backend
      - name: Run frontend tests
        run: npm run test --workspace=apps/frontend
      - name: Run Playwright E2E tests
        run: npx playwright install && npx playwright test tests/e2e/ --reporter=list
      - name: Docker Compose Build
        run: docker-compose build
      - name: Docker Compose Up (detached)
        run: docker-compose up -d
      - name: Healthcheck Backend
        run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:4000/health || exit 1
      - name: Healthcheck Frontend
        run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:5173 || exit 1
      - name: Docker Compose Down
        if: always()
        run: docker-compose down
